env:
  github_domain: 'api.github.com'
modules:
  - name: github_user
    domain: '${github_domain}'
    protocol: https
    url_prefix: /users
    requests:
      - name: user_profile
        path: /psf
